uniplaces/uniplaces-uniq

src/styles/_common/_colors.scss
src/styles/_components/_alerts.scss
src/styles/_components/_badges.scss
src/styles/_components/_cards.scss
src/styles/_components/_pagination.scss
src/styles/_components/_toasts.scss
src/styles/_components/_tooltips.scss
src/styles/_components/_widgets.scss
src/styles/main.scss

https://uniplaces.atlassian.net/browse/UN-4109
New component styles - alert messages && cards.

[RFC][UN-4109] Build the components

---

src/images/check-icon.svg
src/images/toggle-off-icon.svg
src/images/toggle-on-icon.svg
src/styles/_common/_typography.scss
src/styles/_components/_animations.scss
src/styles/_components/_dropdowns.scss
src/styles/_components/_input.scss
src/styles/_components/_tabs.scss
src/styles/_components/_toggles.scss

https://uniplaces.atlassian.net/browse/UN-4111

[RFC][UN-4111] Build the templates

---

src/styles/_components/_toasts.scss

Fixed uniq's modal namming conflict

[RFC][NI] Fixed modal display @ bookings

---

src/styles/_common/_typography.scss
src/styles/_components/_alerts.scss
src/styles/_components/_buttons.scss
src/styles/_components/_dropdowns.scss
src/styles/_components/_grid.scss
src/styles/_components/_labels.scss
src/styles/_components/_tabs.scss
src/styles/_components/_toasts.scss
src/styles/_components/_toggles.scss
src/styles/_components/_tooltips.scss

Refers to: https://uniplaces.atlassian.net/browse/UN-5279
Fixed default styles to match current design && added new tooltip component styles.

[RFC][UN-5279] Update the styleguide

---

src/styles/_common/_colors.scss

fixed primary light color version

[RFC][NI] Fix header dropdown item hovered background color 

---

.vscodeignore
bower.json
src/index.html
src/styles/_common/_colors.scss
src/styles/_common/_grid.scss
src/styles/_common/_typography.scss
src/styles/_common/_variables.scss
src/styles/_components/_alerts.scss
src/styles/_components/_animation.scss
src/styles/_components/_header.scss
src/styles/_components/_image-gallery.scss
src/styles/_components/_info-box.scss
src/styles/_components/_inputs.scss
src/styles/_components/_progress-bar.scss
src/styles/_components/_step-card.scss
src/styles/_main.scss
src/styles/demo.scss

v2.0.1
Setting up new styles to be used inside an ember-addon.

[RFC][NI] V2.0.1 - new styles for ember-addon

---

src/index.html
src/styles/_common/_grid.scss
src/styles/_common/_reset.scss
src/styles/_common/_variables.scss
src/styles/_components/_alerts.scss
src/styles/_components/_info-box.scss
src/styles/_components/_inputs.scss
src/styles/_components/_modals.scss
src/styles/demo.scss

Added new component styles - grid and alerts and some other minor improvements.

[RFC][NI] Add Grid and alert components && minor fixes

---

bower.json
src/index.html
src/styles/_common/_colors.scss
src/styles/_common/_reset.scss
src/styles/_components/_alerts.scss
src/styles/_components/_buttons.scss
src/styles/_components/_header.scss
src/styles/_components/_info-box.scss
src/styles/_components/_inputs.scss
src/styles/demo.scss

Refers to: https://uniplaces.atlassian.net/browse/UN-6614
Several fixes to match UniQ's ember addon styles

[RFC][UN-6614] Improvements to uniq

---

src/styles/_components/_inputs.scss

Hot-fix for issue preventing input error state styling from be applied.

[RFC][NI] Fixed input--error

---

bower.json
src/styles/_components/_buttons.scss

Hot-fix for issue preventing button disabled state styling from be applied.

[RFC][NI] Fixed --disabled selector in buttons

---

bower.json
src/styles/_components/_inputs.scss

Hot-fix for issue preventing input-button disabled state styling from being applied.

[RFC][NI] Fixed :disabled selector in input-button mixin

---

bower.json
src/styles/_common/_reset.scss

[RFC][NI] Fix map dragging styles (Hotfix)

---

src/styles/_components/_inputs.scss

New barebones style for the textarea element

[RFC][NI] New barebones style for the textarea element

---

bower.json
src/index.html
src/styles/_common/_colors.scss
src/styles/_common/_fonts.scss
src/styles/_common/_typography.scss
src/styles/_components/_buttons.scss
src/styles/_components/_header.scss
src/styles/_components/_image-gallery.scss
src/styles/_components/_info-box.scss
src/styles/_components/_inputs.scss
src/styles/_components/_modals.scss
src/styles/_components/_step-card.scss
src/styles/_main.scss
src/styles/demo.scss

Refers to: https://uniplaces.atlassian.net/browse/UN-6730
**Warning**: be mindful that this version will break typography on all platforms right at a build level. Thus making changes on every platforms that update to this version is imperative.

[RFC][UN-6730] New design changes

---

src/styles/_components/_image-gallery.scss

Fixed remove button styles on the image gallery

[RFC][NI] Fix remove button styles on image gallery

---

src/styles/_components/_info-box.scss

[RFC][NI] hot fix for info box styling

---

src/styles/_components/_inputs.scss

hot fix for the uni input price borders

[RFC][NI] Hot fix - Uni input price borders (on focus)

---

bower.json
src/styles/_components/_inputs.scss

https://uniplaces.atlassian.net/browse/UN-6972

[RFC][UN-6972] Add uni-select styles

---

src/styles/_components/_inputs.scss

[RFC][NI] Add :focus styles to select input

---

bower.json
src/index.html
src/styles/_common/_colors.scss
src/styles/_common/_typography.scss
src/styles/_components/_forms.scss
src/styles/_components/_modals.scss
src/styles/_main.scss
src/styles/demo.scss

Refers to: https://uniplaces.atlassian.net/browse/UN-7010
Created styles and structure for the new signup component
Step 1:
Step 2:

[RFC][UN-7010] Create sign-up component on the uniq and ember addon

---

src/index.html
src/styles/_components/_forms.scss
src/styles/_components/_modals.scss
src/styles/demo.scss

Refers to: https://uniplaces.atlassian.net/browse/UN-7100
Added sign-in component styles

[RFC][UN-7100] Create sign-in component on the uniq

---

src/styles/_components/_forms.scss

Removed back button from signup title

[RFC][NI] Fix sign up title back button

---

src/index.html
src/styles/_common/_colors.scss
src/styles/_components/_footer.scss
src/styles/_components/_tabs.scss
src/styles/_main.scss
src/styles/demo.scss

Refers to: https://uniplaces.atlassian.net/browse/UN-7156
Added new tabs component and reviewed max width styles.

[RFC][UN-7156] Self-service tabs on the uniq

---

bower.json
src/styles/_components/_carroussel.scss
src/styles/_main.scss

Refers to: https://uniplaces.atlassian.net/browse/UN-7216
Added carroussel styles

[RFC](UN-7216] Create styles for carrousel component

---

src/styles/_components/_carrousel.scss
src/styles/_main.scss

[RFC][NI] Minor Carrousel name fix

---

src/index.html
src/styles/_components/_info-box.scss

[RFC][NI] Add icon help on mobile

---

src/styles/_common/_colors.scss

[RFC][NI] Add new modal colors

---

src/styles/_common/_colors.scss

[RFC][NI] Add new progress bar colors

---

src/styles/_common/_colors.scss

[RFC][NI] Added new progress bar colors

---

src/styles/_common/_colors.scss
src/styles/_components/_footer.scss

We need to refactor to give a better naming to the existing `footer` mixin (it is used like a navigation footer on self-service).
I think the one implemented in this PR should be the footer mixin, as it is a breaking change, it is not done here. At the moment this one is named `footer-website`
https://uniplaces.atlassian.net/browse/UN-7174

[RFC][UN-7174] Added new footer mixin

---

src/index.html
src/styles/_components/_header.scss

Refers to: https://uniplaces.atlassian.net/browse/UN-7304
Added mobile header menu

[RFC][UN-7304] Create header menu for mobile

---

src/styles/_components/_inputs.scss

[RFC][NI] Add mobile-number input error focus

---

src/styles/_components/_tabs.scss

NI 
Update _tabs.scss
removed min-width from each tab item to fit all in smaller screens.

[RFC][NI] Fix tabs item width

---

src/styles/_components/_footer.scss

Adds dark theme in footer. 
Sorry for overqualification but that's the simplest way of creating a dark theme and not adding modifiers to every single element 😞

[RFC][NI] Added dark theme for footer

---

src/styles/_common/_colors.scss
src/styles/_components/_footer.scss

[RFC][NI] Using uniq's variables to colors, added fill-opacity

---

src/index.html
src/styles/_components/_animation.scss
src/styles/_components/_header.scss
src/styles/demo.scss

NI
Refactored mobile header nav animation

[RFC][NI] Fix mobile header menu animations

---

src/styles/_components/_forms.scss

[RFC][NI] Minor fix to signup text spacing

---

src/styles/_components/_header.scss
src/styles/_components/_info-box.scss
src/styles/_components/_inputs.scss
src/styles/_components/_messages.scss
src/styles/_components/_modals.scss

https://uniplaces.atlassian.net/browse/UN-7405

[RFC][UN-7405] Improvements on uni-input-price and landing page buttons on safari

---

src/styles/_components/_inputs.scss

[RFC][NI] Fix select styles in firefox

---

bower.json
src/styles/_components/_footer.scss

NI
several fixes to footer styles

[RFC][NI] Footer alignment fixes

---

src/styles/_components/_inputs.scss

[RFC][NI] Add input-price modifier focused

---

src/styles/_common/_colors.scss

[RFC][NI] Fix gallery item border-color

---

bower.json
src/styles/_components/_inputs.scss

[RFC][NI] Fix textarea border

---

bower.json
src/styles/_components/_buttons.scss
src/styles/_components/_inputs.scss
src/styles/_components/_step-card.scss

[RFC][NI] Fix textarea borders

---

bower.json
src/styles/_common/_colors.scss
src/styles/_components/_alerts.scss

NI
Created generic alert-banner component to use as the cookie message.

[RFC][NI] Create Cookie alert banner

---

src/styles/_components/_alerts.scss

https://uniplaces.atlassian.net/browse/UN-7574

[RFC][UN-7574] Add error modifier to alert

---

src/styles/_common/_reset.scss

[RFC][NI] Fixed scrollbar visibility

---

src/index.html
src/styles/_common/_colors.scss
src/styles/_common/_reset.scss
src/styles/_components/_alerts.scss
src/styles/demo.scss

NI
Several fixes to cookie alert banner.

[RFC][NI] Fixes to cookie alert banner

---

src/styles/_common/_colors.scss
src/styles/_common/_reset.scss
src/styles/_components/_forms.scss

https://uniplaces.atlassian.net/browse/UN-7645

[RFC][UN-7714] signup improvements

---

src/styles/_common/_colors.scss

fix to this PR https://github.com/uniplaces/uniplaces-uniq/pull/72

[RFC][UN-7714] signup improvements fix

---

src/styles/_common/_colors.scss

fix to this PR: https://github.com/uniplaces/uniplaces-uniq/pull/73

[RFC][UN-7714] signup improvements fix 2

---

src/styles/_components/_header.scss

[RFC][NI] Fix unexistent color

---

src/styles/_common/_colors.scss
src/styles/_components/_inputs.scss
src/styles/_components/_modals.scss

https://uniplaces.atlassian.net/browse/UN-7730

[RFC][UN-7730] Overall improvements on several components

---

src/styles/_components/_inputs.scss

[RFC][NI] Minor fix in input price focused color

---

src/styles/_common/_colors.scss
src/styles/_components/_status-tags.scss
src/styles/_main.scss

I think this should be a component because probably will be used in more areas of the different platforms.
Example of use: In the new Management-Enquires area of AP
https://projects.invisionapp.com/d/main/default/#/console/10009152/215179492/preview
ps: The new colors should be added to the uniq colors

[RFC][NI] New component for status tags or labels

---

src/styles/_common/_colors.scss
src/styles/_components/_status-tags.scss

Mixin declaration was missing and unnecessary quotes where left on the hexadecimal colors
(Sorry)

[RFC][NI]Fixed mixin declaration and quotes

---

src/styles/_common/_media.scss

Desktop-first stays default
Added ‘min’ and ‘max’ options

Added mobile-first support for the breakpoint mixin

---

src/styles/_components/_alerts.scss

[RFC][NI] Minor fix to cookie alert

---

bower.json
src/styles/_common/_colors.scss
src/styles/_components/_alerts.scss
src/styles/_components/_forms.scss
src/styles/_components/_image-gallery.scss

[RFC][NI] Minor fix to dropdowns

---

src/styles/_components/_inputs.scss

[RFC][NI] Minor fix in select focus border color

---

src/styles/_components/_image-gallery.scss

[RFC][NI] Fix photo upload main picker color

---

src/styles/_common/_grid.scss
src/styles/_common/_helpers.scss
src/styles/_common/_variables.scss
src/styles/_main.scss

New _helpers file to receive global helpers and utilities
uni-clearfix removed from the _grid file and added to the new _helpers file
This away can use it on float layouts

[RFC][NI]New helper file to have global helpers like the uni-clearfix mixin

---

src/styles/_common/_variables.scss

Added align-content. Useful for vertical aligns based on flex box model.

[RFC][NI]updated flex mixins

---

src/index.html
src/styles/_common/_colors.scss
src/styles/_components/_tooltip.scss
src/styles/_main.scss
src/styles/demo.scss

https://uniplaces.atlassian.net/browse/UN-7908

[RFC][UN-7908] Adds tooltip mixin

---

src/styles/_common/_helpers.scss

- One micro-clearfix that differs from uni-clearfix in terms of box model. There are use cases for both.
- One text-truncate feature to display “…” in longer strings

[RFC][NI]Added 2 new helper mixins

---

bower.json
src/styles/_common/_colors.scss
src/styles/_components/_tooltip.scss

This changes tooltip positioning and content, content is now absolute as
it must be over other elements. Alignement is now relative so tooltip is
at top right of icon by default

[RFC][NI] Changes positioning of tooltip and content

---

bower.json
src/styles/_common/_colors.scss
src/styles/_components/_status-tags.scss

Updated colors for status tags
Updated bower.json version

[RFC][NI]Updated colors for status tags

---

bower.json
src/styles/_common/_helpers.scss

New helper to hide elements while at the same time make them accessible

[RFC][NI]visually-hidden helper

---

bower.json
src/styles/_components/_header.scss

Fixed mobile menu (as part of the solution to https://uniplaces.atlassian.net/browse/UN-8051).

[RFC][NI] Mobile menu improvements self service

---

src/styles/_components/_header.scss

[RFC][NI] Header mobile nav fix

---

bower.json
src/styles/_common/_variables.scss
src/styles/_components/_image-gallery.scss

[RFC][NI] Fix image gallery positioning

---

src/styles/_components/_buttons.scss

[RFC][NI] Update disabled button border

---

src/styles/_common/_colors.scss
src/styles/_components/_inputs.scss

[RFC][NI] Add radio button disabled style

---

src/styles/_components/_alerts.scss

[RFC][NI] fixed alerts's links

---

bower.json
src/styles/_common/_typography.scss

Change headline mixin to also support 38px for fontsize and also add label mixin

[RFC] Change headline mixin to also support 38px for fontsize and also add label mixin

---

bower.json
src/styles/_common/_media.scss

Added new breakpoint required for targeting mobile (landscape) devices;

[RFC][NI] Add new breakpoint

---

src/styles/_components/_footer.scss

[RFC][NI] Fix footer unexistent font

---

bower.json
src/styles/_components/_multi-selector.scss

[RFC] fix line-height in multi-selector 

---

src/index.html
src/styles/_components/_multi-selector.scss

- more flexible
- warning/error

[RFC][UN-8887] improvements on multi-selector - more flexible

---

bower.json
src/index.html
src/styles/_common/_colors.scss
src/styles/_components/_inputs.scss
src/styles/demo.scss

[RFC][NI] fixed input's padding and border

---

bower.json
src/styles/_components/_inputs.scss

https://uniplaces.atlassian.net/browse/UN-8888
Screenshots:
After:
Before:

[RFC][UN-8888] Fix textarea placeholder font-size

---

bower.json
src/styles/_common/_colors.scss

Will be used to fix: https://uniplaces.atlassian.net/browse/UN-8793
Added new colors for the calendar component

[RFC][NI] Added new calendar colors

---

src/styles/_common/_colors.scss

[RFC][NI] Remove unused color

---

src/index.html
src/styles/_components/_inputs.scss
src/styles/demo.scss

[RFC][NI] update mobile-number

---

bower.json
src/styles/_common/_colors.scss

input text color was not according the design framework
- before
- after

[RFC][NI] fixed input text color

---

src/styles/_components/_step-card.scss

https://uniplaces.atlassian.net/browse/UN-9887

[RFC][NI] Update step card

---

src/styles/_components/_progress-bar.scss

Supports as part of the solution to: https://uniplaces.atlassian.net/browse/UN-10457
fix progressbar styles

[RFC][NI] Fix progress bar styles

---

src/index.html
src/styles/_components/_header.scss

https://uniplaces.atlassian.net/browse/UN-14252
**TL;DR: fixed mobile header styles**

[RFC][UN-14252] Improve sign up on uniplaces uniq

---

src/styles/_common/_fonts.scss

NI
Update _fonts.scss to remove unnecessary font-family rules, as the actual fonts are placed on a per project basis.

[RFC][NI] Remove font families from UniQ
